version: '3'

services:

  zeppelin:
    image: apache/zeppelin:0.8.1
    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_LOG_DIR: '/logs'
      ZEPPELIN_NOTEBOOK_DIR: '/notebook'
    ports:
      - 8080:8080
    volumes:
      - ./zeppelin/logs:/logs
      - ./zeppelin/notebook:/notebook
    depends_on:
      - postgresdb
      - minio
    networks:
      - zepnet

  minio:
    image: minio/minio:RELEASE.2019-05-23T00-29-34Z
    ports:
      - 9000:9000
    volumes:
      - ./test/.minio/data:/export
      - ./test/.minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    networks:
      - zepnet
    command: minio server /data
#
      #  createbuckets:
      #    image: minio/mc:RELEASE.2019-05-23T01-33-27Z
      #    volumes:
      #      - ./minio/initdata:/initdata
      #    depends_on:
      #      - minio
      #    environment:
      #      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      #      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      #      MINIO_BUCKET: ${MINIO_BUCKET}
      #    entrypoint: >
      #      /bin/sh -c "
      #      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      #      /usr/bin/mc mb myminio/${MINIO_BUCKET};
      #      /usr/bin/mc cp /initdata/bank.csv myminio/${MINIO_BUCKET};
      #      /usr/bin/mc ls myminio;
    #      exit 0;
    #      "

  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_ZEPPELIN_USER: ${POSTGRES_USER}
      POSTGRES_ZEPPELIN_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ZEPPELIN_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - 8081:5432
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    networks:
      - zepnet

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb
    ports:
      - 8082:8080
    depends_on:
      - postgresdb
    networks:
      - zepnet

networks:
  zepnet: