version: '3'

services:

  zeppelin:
    image: apache/zeppelin:0.8.1
    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_LOG_DIR: '/logs'
      ZEPPELIN_NOTEBOOK_DIR: '/notebook'
    ports:
      - 8080:8080
    volumes:
      - ./zeppelin/logs:/logs
      - ./zeppelin/notebook:/notebook
      - ./zeppelin/conf/zeppelin-env.sh:/zeppelin/conf/zeppelin-env.sh
      #- ./zeppelin/properties:/app/properties
      - ./zeppelin/libs:/app/libs
    networks:
      - zepnet

  minio:
    image: minio/minio:RELEASE.2019-05-23T00-29-34Z
    ports:
      - 8083:9000
    volumes:
      - ./minio/data:/data
      #- ./minio/config/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: minio server /data
    networks:
      - zepnet

  webdav:
    image: bytemark/webdav
    ports:
      - "8083:80"
    environment:
      AUTH_TYPE: Basic
      USERNAME: zeppelin
      PASSWORD: zeppelin
    volumes:
      - ./webdav:/var/lib/dav
    networks:
      - zepnet

  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_ZEPPELIN_USER: ${POSTGRES_USER}
      POSTGRES_ZEPPELIN_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ZEPPELIN_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - 8081:5432
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    networks:
      - zepnet

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb
    ports:
      - 8082:8080
    depends_on:
      - postgresdb
    networks:
      - zepnet

networks:
  zepnet:
    driver: bridge
