version: '3'

services:

  zeppelin:
    build:
      context: ./zeppelin/docker
    ports:
      - 10000:8080
    volumes:
      - ./zeppelin/logs:/opt/logs
      - ./zeppelin/notebook:/opt/notebook
      - ./zeppelin/files:/opt/files
      - ./zeppelin/conf/interpreter.json:/zeppelin/conf/interpreter.json
    networks:
      - zepnet

  minio:
    image: minio/minio:RELEASE.2019-05-23T00-29-34Z
    ports:
      - 10004:9000
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: minio server /data
    networks:
      - zepnet

  webdav:
    image: bytemark/webdav
    ports:
      - 10003:80
    environment:
      AUTH_TYPE: Basic
      USERNAME: ${WEBDAV_USERNAME}
      PASSWORD: ${WEBDAV_PASSWORD}
    volumes:
      - ./webdav:/var/lib/dav
    networks:
      - zepnet

  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_ZEPPELIN_USER: ${POSTGRES_USER}
      POSTGRES_ZEPPELIN_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ZEPPELIN_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - 10001:5432
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - zepnet

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb
    ports:
      - 10002:8080
    depends_on:
      - postgresdb
    networks:
      - zepnet

networks:
  zepnet:
    driver: bridge
